# permissions for end users to view deadlinejobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deadlinejob-viewer-role
rules:
- apiGroups:
  - job.nuka137.com
  resources:
  - deadlinejobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - job.nuka137.com
  resources:
  - deadlinejobs/status
  verbs:
  - get
