
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - job.nuka137.com
  resources:
  - deadlinejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - job.nuka137.com
  resources:
  - deadlinejobs/finalizers
  verbs:
  - update
- apiGroups:
  - job.nuka137.com
  resources:
  - deadlinejobs/status
  verbs:
  - get
  - patch
  - update
